import type { Content } from './en'

export const es: Content = {
  nav: {
    about: 'Sobre mí',
    experience: 'Experiencia',
    projects: 'Proyectos',
    skills: 'Habilidades',
    education: 'Educación',
    contact: 'Contacto',
  },
  hero: {
    available: 'Ingeniero de Software Senior',
    role: 'Full-Stack · Cloud · Arquitectura',
    headline: 'Convierto monolitos en sistemas escalables.',
    summary:
      '9+ años diseñando y entregando plataformas de microservicios y serverless en AWS, GCP y Azure. TypeScript, NestJS, Vue y PostgreSQL, con principios SOLID y CI/CD automatizado.',
    ctaProjects: 'Ver proyectos',
    ctaCv: 'Descargar CV',
    ctaContact: 'Contáctame',
    location: 'México · Remoto',
  },
  about: {
    eyebrow: 'Sobre mí',
    title: 'Ingeniería que escala con el negocio',
    paragraphs: [
      'Soy Ingeniero de Software Full-Stack Senior con más de 9 años de experiencia diseñando y orquestando la transformación arquitectónica de sistemas monolíticos hacia microservicios y entornos serverless (AWS).',
      'Trabajo en todo el stack con JavaScript/TypeScript, Node.js/NestJS y Vue.js, con sólida experiencia en diseño de bases de datos relacionales (PostgreSQL / SQL Server), DevOps, Docker y automatización CI/CD. Me enfoco en aplicar principios SOLID y entregar soluciones escalables y mantenibles.',
      'También construyo mis propios productos de principio a fin: el backend de una plataforma de transporte, un SaaS multi-tenant para agencias de viajes y herramientas de gestión para un negocio familiar y un comedor comunitario sin fines de lucro.',
    ],
    stats: [
      { value: '9+', label: 'Años de experiencia' },
      { value: '3', label: 'Nubes: AWS, GCP, Azure' },
      { value: '4', label: 'Productos independientes' },
      { value: 'ES · EN', label: 'Español nativo, inglés B2' },
    ],
  },
  experience: {
    eyebrow: 'Experiencia',
    title: 'Dónde he trabajado',
    present: 'Actualidad',
    client: 'Cliente',
    roles: [
      {
        id: 'alluxi',
        title: 'Ingeniero de Software Senior',
        company: 'Alluxi S.A. de C.V.',
        client: 'E-days (Reino Unido)',
        location: 'Remoto, México',
        period: 'Dic 2025 – Actualidad',
        bullets: [
          'Desarrollo de nuevos módulos para una plataforma de gestión de ausencias y RR. HH.',
          'Construcción del módulo de distribución de asignaciones de empleados para la operación de los tenants.',
          'Implementación de un portal de carga de documentos para la gestión de archivos por tenant.',
          'Mantenimiento de un constructor de flujos de trabajo para automatizar procesos.',
          'Pruebas unitarias para endpoints del backend.',
        ],
      },
      {
        id: 'raddatz',
        title: 'Ingeniero de Software Senior (Freelance)',
        company: 'RADDATZ Productos Maderables',
        location: 'Remoto, México',
        period: 'Feb 2025 – Sep 2025',
        bullets: [
          'Lideré el desarrollo de punta a punta de la primera suite de software de la empresa, del diseño a producción.',
          'Diseñé una arquitectura de microservicios con NestJS y NATS (Inventario, Nómina, Compras).',
          'Construí 2 apps móviles (React Native + Expo Router) para seguimiento de producción y materia prima.',
          'Implementé pipelines CI/CD con Docker, Railway, GitHub Actions y AWS S3 / CloudFront.',
          'Diseñé una arquitectura PostgreSQL multi-schema escalable.',
        ],
      },
      {
        id: 'xid',
        title: 'Ingeniero de Software Senior',
        company: 'XID - Digital Services, S.A. de C.V.',
        client: 'Grupo Lomas',
        location: 'Remoto, México',
        period: 'Jun 2023 – Ene 2025',
        bullets: [
          'Migré un monolito en PHP a microservicios (NestJS) y microfrontends (Vue 3).',
          'Rediseñé la arquitectura de base de datos y mejoré el rendimiento del backend.',
          'Integré PayPal y un sistema de pagos en el flujo de reservaciones.',
          'Desplegué servicios con Docker en GCP Cloud Run.',
          'Lideré el análisis de requerimientos y la transferencia de conocimiento al equipo del cliente.',
        ],
      },
      {
        id: 'ion',
        title: 'Ingeniero de Software Semi-Senior',
        company: 'ION Financiera S.A.P.I. de C.V. SOFOM, E.R.',
        location: 'Remoto, México',
        period: 'Oct 2021 – Jun 2023',
        bullets: [
          'Desarrollé APIs serverless (AWS Lambda + API Gateway) para procesos de crédito, con logging en CloudWatch.',
          'Escribí pruebas unitarias para funciones Lambda con Jest.',
          'Implementé simuladores de crédito y reglas de negocio para flujos de aprobación de crédito hipotecario.',
          'Lideré la migración a un nuevo sistema Core garantizando la integridad de los datos.',
          'Mantuve y mejoré el frontend en Vue 3 para la gestión de clientes y pagos.',
        ],
      },
    ],
    earlierTitle: 'Experiencia previa',
    earlier: [
      {
        title: 'Ingeniero de Software Junior',
        company: 'Guadiana Tecnología',
        location: 'Durango',
        period: 'Nov 2019 – Sep 2021',
        description:
          'Interfaz en React para un sistema de permisos, validación fiscal con OCR y refactorización del control de acceso heredado para las minas de First Majestic (C#, ASP.NET, React, SQL Server).',
      },
      {
        title: 'Ingeniero de Software Junior',
        company: 'SC Computación',
        location: 'Durango',
        period: 'Ene 2017 – Nov 2019',
        description:
          'Sistemas empresariales en .NET y optimización de SQL Server para CFDI, contabilidad e inventarios.',
      },
    ],
  },
  projects: {
    eyebrow: 'Proyectos',
    title: 'Proyectos independientes',
    intro:
      'Productos que diseño y construyo de punta a punta, desde el modelo de datos y las APIs hasta el despliegue.',
    items: [
      {
        id: 'ride',
        name: 'Ride',
        tagline: 'Backend de una plataforma de transporte en tiempo real',
        role: 'Líder de Backend',
        context: 'Freelance, equipo pequeño',
        period: 'Abr 2026 – Actualidad',
        bullets: [
          'Lideré el backend: ciclo de vida del viaje, asignación de conductores y seguimiento GPS en vivo mediante un gateway Socket.io escalado con Redis GEO.',
          'Diseñé un ledger de billetera para conductores con liquidación ACID de viajes en PostgreSQL; integré Stripe, autenticación con Clerk y notificaciones push.',
        ],
      },
      {
        id: 'arada',
        name: 'Arada',
        tagline: 'SaaS multi-tenant para agencias de viajes',
        role: 'Creador y Desarrollador Full-Stack',
        context: 'Producto propio',
        period: 'Ago 2026 – Actualidad',
        bullets: [
          'Implementé aislamiento de tenants fail-closed con una extensión de Prisma Client y llaves foráneas compuestas.',
          'Diseñé planes de suscripción por niveles con feature flags; desplegué 4 servicios mediante infraestructura como código.',
        ],
      },
      {
        id: 'lignum',
        name: 'Lignum Vitae',
        tagline: 'Plataforma de cotización, inventario y ventas',
        role: 'Creador y Desarrollador Full-Stack',
        context: 'Negocio familiar',
        period: 'Sep 2026 – Actualidad',
        bullets: [
          'Arquitecté un monorepo con pnpm (API NestJS, admin React, landing Astro) que comparte un cliente OpenAPI tipado.',
          'Diseñé un motor puro de costos y precios compartido por la API y el admin; desplegado con infraestructura como código.',
        ],
      },
      {
        id: 'solanus',
        name: 'Comedor Solanus',
        tagline: 'Sistema de gestión para un comedor comunitario',
        role: 'Creador y Desarrollador Full-Stack',
        context: 'Sin fines de lucro, Amigos de los Capuchinos ABP',
        period: 'Sep 2026 – Actualidad',
        bullets: [
          'Construí la plataforma de operación diaria (API NestJS + app web React/Vite): beneficiarios, asistencia, inventario y donadores.',
          'Implementé permisos por rol, dashboards y reportes mensuales en PDF; cubrí los flujos críticos con Jest y Playwright.',
        ],
      },
    ],
  },
  skills: {
    eyebrow: 'Habilidades',
    title: 'Herramientas con las que trabajo',
    groups: {
      backend: 'Backend',
      frontend: 'Frontend',
      databases: 'Bases de datos',
      cloud: 'Nube',
      tools: 'Librerías y pruebas',
      ai: 'Desarrollo asistido por IA',
    },
    softTitle: 'Habilidades blandas',
    soft: [
      'Liderazgo',
      'Comunicación',
      'Mentoría',
      'Proactivo',
      'Resolución de problemas',
      'Colaborativo',
    ],
  },
  education: {
    eyebrow: 'Educación',
    title: 'Educación y formación',
    degree: 'Ingeniería en Sistemas Computacionales',
    school: 'Instituto Tecnológico de Durango',
    period: 'Ago 2014 – Jun 2019',
    coursesTitle: 'Cursos',
    courses: [
      { name: 'React Native Expo: Aplicaciones Nativas para iOS y Android', hours: '25.5 hrs' },
      { name: 'NestJS + Microservicios: Aplicaciones Escalables y Modulares', hours: '21 hrs' },
      { name: 'Docker: Guía Práctica para Desarrolladores', hours: '14 hrs' },
      { name: 'Vue.js: De Cero a Experto', hours: '37.5 hrs' },
      { name: 'TypeScript: Guía Completa', hours: '8.5 hrs' },
      { name: 'Principios SOLID y Clean Code', hours: '6.5 hrs' },
      { name: 'React.js', hours: '44.5 hrs' },
      { name: 'Node.js: De Cero a Experto', hours: '28.5 hrs' },
    ],
    languagesTitle: 'Idiomas',
    languages: [
      { name: 'Español', level: 'Nativo' },
      { name: 'Inglés', level: 'B2 Intermedio-Alto' },
    ],
  },
  contact: {
    eyebrow: 'Contacto',
    title: 'Construyamos algo sólido.',
    text: 'Abierto a oportunidades senior de full-stack y arquitectura. La forma más rápida de contactarme es por correo.',
    email: 'Escríbeme',
    phone: 'Llamar',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    cv: 'Descargar CV',
  },
  footer: { rights: 'Todos los derechos reservados.', top: 'Volver arriba' },
  notFound: {
    title: 'Página no encontrada',
    text: 'La página que buscas no existe o fue movida.',
    back: 'Volver al inicio',
  },
  ui: {
    toggleTheme: 'Cambiar tema',
    toggleLanguage: 'Switch to English',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    skip: 'Saltar al contenido',
  },
}
